package-helm-chart:
  stage: build
  image:
    name: dtzar/helm-kubectl:3.12.3
  before_script:
    - >
      echo ${CI_REGISTRY_PASSWORD} |
      helm registry login
      --username gitlab-ci-token
      --password-stdin
      ${CI_REGISTRY}
  script:
    - mkdir packages
    - "CHART_VERSION=$(helm show chart helm-chart | grep '^version:' | sed 's/version: //')"
    - |
      if [[ -n "${CI_COMMIT_TAG}" ]]
      then
        VERSION=${CI_COMMIT_TAG}
      else
        VERSION=${CHART_VERSION}-pre-${CI_COMMIT_REF_SLUG}
      fi
    - >
      helm package helm-chart
      --destination packages
      --dependency-update
      --version="${VERSION}"
    - |
      echo $CI_REGISTRY_IMAGE
      for chart in packages/*.tgz
      do
        helm push $chart "oci://${CI_REGISTRY_IMAGE}/helm"
      done
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
